# php
php:
  build: php
  ports:
    - "9000:9000"
    - "80:80"
    - "3306:3306"
  volumes:
    - $PWD/src:/src
  working_dir: /src
  environment:
    APP_DIR: /src

# proxy
ngx_mruby:
  build: ngx_mruby
  net: "container:php"
  working_dir: /usr/local/nginx
  volumes_from:
    - php
  environment:
    APP_DIR: /src

# mysql
mysql:
  image: mysql:5.6
  net: "container:php"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
