application: gae-php-sample
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1

- url: /.*
  script: index.php

- url: /index\.html
  script: index.php
